services:
  - type: web
    name: sanyyy-license-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
